<HTML>
<HEAD>
<TITLE> Web Authentication Redirect</TITLE>
<META http-equiv="Cache-control" content="no-cache">
<META http-equiv="Pragma" content="no-cache">
<META http-equiv="Expires" content="-1">
<META http-equiv="refresh" content="1; URL=https://nce-campus.th-luebeck.de:19008/portal?ap%2Dmac=f44588b2d220&redirect%2Durl=https%3A%2F%2Fraw%2Egithubusercontent%2Ecom%2Fmoodlehq%2Fmoodle%2Dplugin%2Dci%2Fmaster%2Fgha%2Edist%2Eyml&ssid=THL%2DGast&uaddress=172%2E31%2E96%2E46&umac=5effef6f9853">
</HEAD>
</HTML>
